//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Employee_Log
    {
        public byte[] Employee_Id { get; set; }
        public Nullable<byte> Rec_Operation { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Job_Title { get; set; }
        public byte[] A_Team_Id { get; set; }
        public byte[] Reports_To_Id { get; set; }
        public byte[] Rn_Employee_User_Id { get; set; }
        public byte[] AS_Konto_Uzytkownika_Id { get; set; }
        public byte[] AS_Jednostka_Banku_Id { get; set; }
        public string Faksymilka { get; set; }
        public string Work_Email { get; set; }
        public string Work_Phone { get; set; }
        public string Pesel { get; set; }
        public byte[] AS_Wlasciciel_Licencji_Id { get; set; }
        public Nullable<byte> Uprawniony_Do_Podpisu_Kr { get; set; }
        public Nullable<byte> Active { get; set; }
        public byte[] Interaction_Workgroup_Id { get; set; }
        public byte[] AS_Grupa_robocza_CC_Id { get; set; }
        public string ACD_ID { get; set; }
        public string Country_Code { get; set; }
        public Nullable<byte> Algorytm_rozmowy_przychodzace { get; set; }
        public Nullable<byte> Hide_Toolbar { get; set; }
        public Nullable<byte> Screen_Pops { get; set; }
        public Nullable<byte> All_IS_Permissions { get; set; }
        public Nullable<byte> Obsluga_rozmow_przychodzacych { get; set; }
        public Nullable<byte> Hide_Login { get; set; }
        public Nullable<byte> Dialer { get; set; }
        public Nullable<byte> Akceptacja_Wylogowania_Dialer { get; set; }
        public Nullable<byte> Weryfikacja_Wysylanie_maili { get; set; }
        public Nullable<byte> Weryfikacja_Wysylanie_maili_pr { get; set; }
        public Nullable<byte> Weryfikacja_Wysylanie_SMS { get; set; }
        public byte[] A_Employee_Log_Id { get; set; }
        public string Rn_Descriptor { get; set; }
        public Nullable<System.DateTime> Rn_Create_Date { get; set; }
        public byte[] Rn_Create_User { get; set; }
        public Nullable<System.DateTime> Rn_Edit_Date { get; set; }
        public byte[] Rn_Edit_User { get; set; }
    }
}
