//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Wniosek_Wideo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_Wniosek_Wideo()
        {
            this.A_Wniosek_Wideo_Krok = new HashSet<A_Wniosek_Wideo_Krok>();
        }
    
        public byte[] A_Wniosek_Wideo_Id { get; set; }
        public string Rn_Descriptor { get; set; }
        public Nullable<System.DateTime> Rn_Create_Date { get; set; }
        public byte[] Rn_Create_User { get; set; }
        public Nullable<System.DateTime> Rn_Edit_Date { get; set; }
        public byte[] Rn_Edit_User { get; set; }
        public string Numer_Wniosku { get; set; }
        public string Pesel { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<System.DateTime> Timestamp_Wniosku { get; set; }
        public byte[] Przypisany_Do { get; set; }
        public Nullable<System.DateTime> Timestamp_Przypisania { get; set; }
        public byte[] Company_Id { get; set; }
        public Nullable<byte> Status { get; set; }
        public byte[] A_Wniosek_Wideo_Krok_Id { get; set; }
        public string Wideo_Url { get; set; }
        public Nullable<byte> Status_Weryfikacji { get; set; }
        public Nullable<System.DateTime> Data_Weryfikacji { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Wniosek_Wideo_Krok> A_Wniosek_Wideo_Krok { get; set; }
    }
}
