//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Wniosek_Wideo_Krok
    {
        public byte[] A_Wniosek_Wideo_Krok_Id { get; set; }
        public string Rn_Descriptor { get; set; }
        public Nullable<System.DateTime> Rn_Create_Date { get; set; }
        public byte[] Rn_Create_User { get; set; }
        public Nullable<System.DateTime> Rn_Edit_Date { get; set; }
        public byte[] Rn_Edit_User { get; set; }
        public byte[] A_Wniosek_Wideo_Id { get; set; }
        public Nullable<byte> Krok { get; set; }
        public Nullable<byte> Status_Kroku { get; set; }
        public string Komunikat_Bledu { get; set; }
        public Nullable<byte> Typ_Akcji { get; set; }
        public string Akcja { get; set; }
        public Nullable<System.DateTime> Data_Rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_Zakonczenia { get; set; }
    
        public virtual A_Wniosek_Wideo A_Wniosek_Wideo { get; set; }
    }
}
