//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.A_Employee_Profil = new HashSet<A_Employee_Profil>();
            this.Employee_Skills = new HashSet<Employee_Skills>();
            this.A_Team_Member = new HashSet<A_Team_Member>();
            this.A_Grupa_Robocza_Pracownika = new HashSet<A_Grupa_Robocza_Pracownika>();
            this.A_Employee_Poswiadczenia = new HashSet<A_Employee_Poswiadczenia>();
        }
    
        public byte[] AS_Grupa_robocza_CC_Id { get; set; }
        public byte[] AS_Konto_Uzytkownika_Id { get; set; }
        public Nullable<int> Poziom_Uprawnien { get; set; }
        public Nullable<byte> Hide_Login { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Home_Phone { get; set; }
        public string Mobile { get; set; }
        public string First_Name { get; set; }
        public byte[] Reports_To_Id { get; set; }
        public string Work_Fax { get; set; }
        public Nullable<System.DateTime> RN_Photo_ED { get; set; }
        public Nullable<byte> Company_Notification { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> Rn_Edit_Date { get; set; }
        public string Work_Phone { get; set; }
        public string Department { get; set; }
        public byte[] Photo { get; set; }
        public byte[] Rn_Edit_User { get; set; }
        public Nullable<byte> Activity_Meeting_Notification { get; set; }
        public string Employee_Number { get; set; }
        public Nullable<System.DateTime> RN_Photo_ET { get; set; }
        public string Address_1 { get; set; }
        public string Job_Title { get; set; }
        public string Last_Name { get; set; }
        public string Address_2 { get; set; }
        public string Home_Fax { get; set; }
        public string RN_Photo_EX { get; set; }
        public byte[] Office_Id { get; set; }
        public string RN_Photo_DE { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public string Address_3 { get; set; }
        public byte[] Reports_To_User_Id { get; set; }
        public byte[] Rn_Employee_User_Id { get; set; }
        public Nullable<byte> Contact_Notification { get; set; }
        public Nullable<System.DateTime> Last_Login_Date { get; set; }
        public string Rn_Descriptor { get; set; }
        public byte[] Rn_Create_User { get; set; }
        public string RN_Photo_FN { get; set; }
        public string Comments { get; set; }
        public string Home_Email { get; set; }
        public string Work_Email { get; set; }
        public Nullable<byte> Active { get; set; }
        public byte[] Employee_Id { get; set; }
        public byte[] Time_Zone_Id { get; set; }
        public Nullable<System.DateTime> Rn_Create_Date { get; set; }
        public Nullable<int> RN_Photo_FZ { get; set; }
        public string Zip { get; set; }
        public string Extension { get; set; }
        public string Title { get; set; }
        public Nullable<byte> Mark_for_Delete { get; set; }
        public string Country { get; set; }
        public string State_ { get; set; }
        public string City { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public byte[] A_Team_Id { get; set; }
        public string ACD_ID { get; set; }
        public Nullable<byte> Screen_Pops { get; set; }
        public Nullable<byte> Hide_eRIC { get; set; }
        public byte[] Interaction_Workgroup_Id { get; set; }
        public Nullable<byte> Hide_Toolbar { get; set; }
        public Nullable<byte> All_IS_Permissions { get; set; }
        public Nullable<byte> Algorytm_rozmowy_przychodzace { get; set; }
        public Nullable<byte> Obsluga_rozmow_przychodzacych { get; set; }
        public byte[] Interaction_Server_Id { get; set; }
        public string Country_Code { get; set; }
        public string Faksymilka { get; set; }
        public Nullable<byte> Test_CC { get; set; }
        public byte[] AS_Jednostka_Banku_Id { get; set; }
        public Nullable<int> EXT_Id { get; set; }
        public string AD_Id { get; set; }
        public string EXT_NrPokoju { get; set; }
        public string Login_domenowy { get; set; }
        public string PP_CUSTOMER { get; set; }
        public string Inicjaly { get; set; }
        public Nullable<byte> Dialer { get; set; }
        public Nullable<double> SRVC_Srednia_ocen { get; set; }
        public Nullable<double> SRVC_Sredni_czas { get; set; }
        public string DEPO_ConsultantLogin { get; set; }
        public Nullable<byte> Weryfikacja_Wysylanie_maili { get; set; }
        public Nullable<byte> Weryfikacja_Wysylanie_maili_pr { get; set; }
        public Nullable<byte> Uprawniony_Do_Podpisu_Kr { get; set; }
        public string Pesel { get; set; }
        public Nullable<byte> Weryfikacja_Wysylanie_SMS { get; set; }
        public Nullable<byte> Akceptacja_Wylogowania_Dialer { get; set; }
        public byte[] AS_Wlasciciel_Licencji_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Employee_Profil> A_Employee_Profil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Skills> Employee_Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Team_Member> A_Team_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Grupa_Robocza_Pracownika> A_Grupa_Robocza_Pracownika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Employee_Poswiadczenia> A_Employee_Poswiadczenia { get; set; }
    }
}
