//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Nullable<byte> Outlook_Sync { get; set; }
        public Nullable<int> Replica_Number { get; set; }
        public string SyncStream_Inbox_Token { get; set; }
        public byte[] WAM_Preferences { get; set; }
        public string Computer { get; set; }
        public Nullable<System.DateTime> Last_Sync_Date { get; set; }
        public Nullable<System.DateTime> Last_Replicate_Date { get; set; }
        public Nullable<System.DateTime> Last_Configure_Date { get; set; }
        public Nullable<byte> Shortcuts_Updated { get; set; }
        public Nullable<int> Source_Prefix { get; set; }
        public string Cal_Settings { get; set; }
        public string Msmq_Address { get; set; }
        public Nullable<System.DateTime> Rn_Create_Date { get; set; }
        public byte[] Rn_Create_User { get; set; }
        public Nullable<int> Transport { get; set; }
        public Nullable<int> MaxSyncMailSize { get; set; }
        public Nullable<int> RemoteMessageLevel { get; set; }
        public Nullable<System.DateTime> Rn_Edit_Date { get; set; }
        public byte[] Users_Id { get; set; }
        public byte[] Cal_Preferences { get; set; }
        public byte[] Language_Id { get; set; }
        public byte[] Rn_Edit_User { get; set; }
        public Nullable<int> Search_Type_Default { get; set; }
        public string Email_Address { get; set; }
        public byte[] Favorites_Tree_Binary { get; set; }
        public string Login_Name { get; set; }
        public byte[] Favorites_Bar_DockState_Binary { get; set; }
        public Nullable<int> Lan_Sequence { get; set; }
        public string Rn_Descriptor { get; set; }
        public Nullable<int> Mobile_Sequence { get; set; }
        public byte[] Outlook_Sync_User_Id { get; set; }
        public byte[] Preferences { get; set; }
        public Nullable<int> Key_Prefix { get; set; }
        public Nullable<byte> Outlook_Sync_Running { get; set; }
        public byte[] Desktop_Binary { get; set; }
        public Nullable<byte> Outlook_Sync_Startup { get; set; }
        public string Database_Ident { get; set; }
        public string LKey { get; set; }
        public string MLKey { get; set; }
        public byte[] Source_DSM_UserId { get; set; }
        public string ULD { get; set; }
        public Nullable<byte> User_Type { get; set; }
        public Nullable<byte> Is_Locked { get; set; }
    }
}
